services:
  web:
    build: .
    container_name: portfolio
    ports:
      - 4321:4321
    environment:
      - NODE_ENV=production
  
  nginx:
    image: nginx:alpine
    container_name: portfolio-nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web